angular.module('datetime.bootstrap.templates', ['datetime.bootstrap.date.tmpl.html', 'datetime.bootstrap.time.tmpl.html']);

angular.module('datetime.bootstrap.date.tmpl.html', []).run(['$templateCache', function($templateCache) {
  'use strict';
  $templateCache.put('datetime.bootstrap.date.tmpl.html',
    '<div dropdown class=dropdown is-open=drops.date style="display: inline-block" auto-close=disabled><div class=form-control><div dropdown class=dropdown is-open=drops.day style="display: inline-block" auto-close=disabled><input class=internal-form-control ng-model=units.day placeholder=dd force-digits=2 clear-zero in-focus=focii.day style="width:2em ; text-align:center"><ul class=dropdown-menu role=menu style="max-height: 300px; overflow-y: auto"><li ng-repeat="d in data.days"><a role=menuitem ng-click="units.day = d.value">{{d.label}}</a></li></ul></div>&nbsp;/&nbsp;<div dropdown class=dropdown is-open=drops.month auto-close=disabled style="display: inline-block"><input class=internal-form-control ng-model=units.month placeholder=mm force-digits=2 clear-zero in-focus=focii.month style="width:2em ; text-align:center"><ul class=dropdown-menu role=menu style="max-height: 300px; overflow-y: auto"><li ng-repeat="m in data.months"><a role=menuitem ng-click="units.month = m.value" stop-propagation>{{m.label}}</a></li></ul></div>&nbsp;/&nbsp;<div dropdown class=dropdown is-open=drops.year auto-close=disabled style="display: inline-block"><input class=internal-form-control ng-model=units.year placeholder=yyyy force-digits=4 clear-zero in-focus=focii.year style="width:4em ; text-align:center"><ul class=dropdown-menu role=menu style="max-height: 300px; overflow-y: auto"><li ng-repeat="y in data.years"><a role=menuitem ng-click="units.year = y.value">{{y.label}}</a></li></ul></div></div><ul class=dropdown-menu role=menu><li ng-repeat="date in data.dates"><a role=menuitem tabindex=-1 ng-click=setDate(date.value)>{{date.label}}</a></li></ul></div>');
}]);

angular.module('datetime.bootstrap.time.tmpl.html', []).run(['$templateCache', function($templateCache) {
  'use strict';
  $templateCache.put('datetime.bootstrap.time.tmpl.html',
    '<div class=form-control><div dropdown class=dropdown is-open=focii.hour style="display: inline-block" auto-close=disabled><input class=internal-form-control ng-model=units.hour placeholder=hh force-digits=2 clear-zero in-focus=focii.hour style="width:2em ; text-align:center"><ul class=dropdown-menu role=menu style="max-height: 300px; overflow-y: auto"><li ng-repeat="h in data.hours"><a role=menuitem ng-click="units.hour = h.value">{{h.label}}</a></li></ul></div><div ng-if=cfg.showMinutes style=display:inline-block>&nbsp;:&nbsp;<div dropdown class=dropdown is-open=focii.minute auto-close=disabled style="display: inline-block"><input class=internal-form-control ng-model=units.minute placeholder=mm force-digits=2 in-focus=focii.minute style="width:2em ; text-align:center"><ul class=dropdown-menu role=menu style="max-height: 300px; overflow-y: auto"><li ng-repeat="m in data.minutes"><a role=menuitem ng-click="units.minute = m.value">{{m.label}}</a></li></ul></div></div><div ng-if="cfg.showMinutes && cfg.showSeconds" style=display:inline-block>&nbsp;:&nbsp;<div dropdown class=dropdown is-open=focii.second auto-close=disabled style="display: inline-block"><input class=internal-form-control ng-model=units.second placeholder=ss force-digits=2 in-focus=focii.second style="width:2em ; text-align:center"><ul class=dropdown-menu role=menu style="max-height: 300px; overflow-y: auto"><li ng-repeat="s in data.seconds"><a role=menuitem ng-click="units.second = s.value">{{s.label}}</a></li></ul></div></div>&nbsp;&nbsp;<div dropdown class=dropdown is-open=focii.period auto-close=disabled style="display: inline-block"><input class=internal-form-control ng-model=units.period force-period in-focus=focii.period style="width:2em ; text-align:center"><ul class=dropdown-menu role=menu style="max-height: 300px; overflow-y: auto"><li ng-repeat="p in data.periods"><a role=menuitem ng-click="units.period = p.value">{{p.label}}</a></li></ul></div></div>');
}]);
